// Seed data for masterdata collections. Idempotent upsert by stable key (code or normalized name).

const vehicles = [
  { regNo: 'EHS041', code: '113' },
  { regNo: 'YAM722', code: '116' },
  { regNo: 'OEG319', code: '118' },
  { regNo: 'YTM725', code: '119' },
  { regNo: 'YTM731', code: '120' },
  { regNo: 'CPX23E', code: '121' },
  { regNo: 'KLJ02F', code: '122' },
  { regNo: 'ERF67K', code: '123' },
  { regNo: 'SUD96N', code: '125' },
  { regNo: 'JWE88G', code: '126' },
  { regNo: 'ZDT16N', code: '127' },
  { regNo: 'ZJR53A', code: '128' },
  { regNo: 'MKY10F', code: '200' },
  { regNo: 'FTS16B', code: '210' },
  { regNo: 'RYJ547', code: '401' },
  { regNo: 'FCA445', code: '402' },
  { regNo: 'Hjullastare', code: '600' },
  { regNo: 'LAGER', code: '99' },
];

const drivers = [
  { code: 'ANBL', name: 'Andreas Blom' },
  { code: 'ANHN', name: 'Anders Harris' },
  { code: 'BOCR', name: 'Bosse Cronwald' },
  { code: 'CAWI', name: 'Calle Windh' },
  { code: 'CHHA', name: 'Christian Harris' },
  { code: 'CHKA', name: 'Christer Karlsson' },
  { code: 'DANI', name: 'Daniel Nilsson' },
  { code: 'DANO', name: 'Daniel Norling' },
  { code: 'ELKA', name: 'Elias Kart' },
  { code: 'EMED', name: 'Emil Edgren' },
  { code: 'FRWI', name: 'Fredrik Wikström Lagergren' },
  { code: 'GUSA', name: 'Gustaf Sandin' },
  { code: 'GÖRO', name: 'Göran Romeborn' },
  { code: 'JALI', name: 'Janne Lilleste' },
  { code: 'JECA', name: 'Jesper Carlsson' },
  { code: 'JITO', name: 'Jimmy Torstensson' },
  { code: 'JOHE', name: 'Jonas Hellberg' },
  { code: 'JOSE', name: 'Johan Sernemo' },
  { code: 'LAGER', name: 'Lagerpersonal' },
  { code: 'LANI', name: 'Lars Nilsson' },
  { code: 'LARO', name: 'Lasse Rosell' },
  { code: 'LITO', name: 'Linus Torgersson' },
  { code: 'MAAN', name: 'Martin Andersson' },
  { code: 'PEFA', name: 'Peter Fager' },
  { code: 'PELE', name: 'Peter Lengfelt' },
  { code: 'POAN', name: 'Pontus Andersson' },
  { code: 'SIER', name: 'Simon Eriksson' },
  { code: 'STBA', name: 'Stefan Baatz' },
  { code: 'STKO', name: 'Stefan Korneliusson' },
  { code: 'TIAX', name: 'Tim Axelsson' },
  { code: 'ULHE', name: 'Ulf Hellberg' },
];

const customers = [
  { name: 'AB Nord Frakt', address: 'Stormyrlidsvägen 112', city: 'Tärnaby', active: true },
  { name: 'AJAB Smide AB', address: 'Lisslarps Industriområde', city: 'Håcksvik', active: true },
  { name: 'Ale Portar AB', address: 'Göteborgsvägen 29', city: 'Älvängen', active: true },
  { name: 'All-Coating Industrilackering', address: 'E A Rosengrensgata 36', city: 'Västra Frölunda', active: true },
  { name: 'Allround Lack AB', address: 'Återbruksvägen 2', city: 'Göteborg', active: true },
  { name: 'Alviks Trafik AB', address: 'Handelsvägen 2', city: 'Luleå', active: true },
  { name: 'Alvikstrafik', address: 'Alviksvägen 87', city: 'Luleå', active: true },
  { name: 'Andreas Åkerblom Trans AB', address: 'Åsebyösterväg 9', city: 'Kode', active: true },
  { name: 'Andreasson Transport AB Martin', address: 'Groland 6595', city: 'Spekeröd', active: true },
  { name: 'Arendals Maskin&Matrialhantering AB', address: 'Driftgatan 5', city: 'Göteborg', active: true },
  { name: 'Assa Abloy Entrance System Pedestrian AB', address: 'Box 353', city: 'Landskrona', active: true },
  { name: 'Assa Abloy Industrial Sverige AB', address: 'Box 5087', city: 'Västra Frölunda', active: true },
  { name: 'Baltens', address: 'Box 175', city: 'Lindome', active: true },
  { name: 'Beijer Byggmaterial', address: 'Box 860 Filial 019', city: 'Strömsund', active: true },
  { name: 'BilExpressen', address: 'Hildedalsgatan 28b', city: 'Göteborg', active: true },
  { name: 'Björlanda Gård', address: 'Björlanda Strand 41', city: 'Torslanda', active: true },
  { name: 'Boatmanager Näset AB', address: 'Östrahamngatan 41', city: 'Göteborg', active: true },
  { name: 'Boja Port AB', address: 'Björnebergsvägen 21', city: 'Jönköping', active: true },
  { name: 'Bosac AB', address: 'Rörvall 160', city: 'Brastad', active: true },
  { name: 'Bovalls Dörrbyggeri', address: 'Fabriksgatan 2', city: 'Bovallstrand', active: true },
  { name: 'BRA Bygg AB', address: 'Box 99', city: 'Mölndal', active: true },
  { name: 'Braås Åkeri AB', address: 'Åkarevägen 1', city: 'Braås', active: true },
  { name: 'Bröderna Smedberg', address: 'Fabriksgatan 6', city: 'Rydaholm', active: true },
  { name: 'BST Brandskyddsteamet AB', address: 'FE 780', city: 'Uppsala', active: true },
  { name: 'Byggnads firman Reidar Olsson&CO AB', address: 'Kängavägen 11', city: 'Fotö', active: true },
  { name: 'CJ Portar AB', address: 'Nils-Erikssonsgatan 11', city: 'Falköping', active: true },
  { name: 'Cold Star Logistic AB', address: '', city: '', active: true },
  { name: 'Colmec AB', address: 'Box 675', city: 'Norrköping', active: true },
  { name: 'Containertjänst i Tyresö AB', address: 'Lyftkransvägen 23', city: 'Tyresö', active: true },
  { name: 'Convesta svenska AB', address: 'Box 5176', city: 'Göteborg', active: true },
  { name: 'Crawford Production AB (SLT)', address: '', city: '', active: true },
  { name: 'CrawfordCenter Lomma', address: 'Järngatan 14', city: 'Lomma', active: true },
  { name: 'Dahlins Golv i Göteborg AB', address: 'Hildedalsgatan 24', city: 'Göteborg', active: true },
  { name: 'Dala El & Port AB-Falun', address: 'Krontallsvägen 24 A', city: 'Falun', active: true },
  { name: 'Dala Frakt och Logistik AB', address: 'Box 116', city: 'Leksand', active: true },
  { name: 'Dala Svets & Smide AB', address: 'Zettergrensväg 16', city: 'Falun', active: true },
  { name: 'DB Schenker', address: 'Lagervägen17 Box3778', city: 'Umeå', active: true },
  { name: 'Derome Byggvaror & Träteknik AB', address: 'Bjurumsvägen 14', city: 'Veddige', active: true },
  { name: 'Designcontrol', address: 'Kungsporten 2A', city: 'Billdal', active: true },
  { name: 'DFDS Logistics Services AB', address: 'Box 8978', city: 'Göteborg', active: true },
  { name: 'DHL Express (ASSA)', address: 'Hangarvägen 1', city: 'Torslanda', active: true },
  { name: 'DHL Express (Tung)', address: 'Hangarvägen 1', city: 'Torslanda', active: true },
  { name: 'Diedenporten AB', address: 'Industrigatan 3', city: 'Broby', active: true },
  { name: 'Door System i Skellefteå AB', address: 'Box 775', city: 'Piteå', active: true },
  { name: 'DSV Road AB', address: 'Österleden 201', city: 'Landskrona', active: true },
  { name: 'E3 Spedition Transport A/S', address: 'Postbox 159', city: 'Padborg', active: true },
  { name: 'EAB AB', address: 'Stålgatan 2', city: 'Smålandsstenar', active: true },
  { name: 'ECM Office Supplies AB', address: 'Gamla Kronvägen 35', city: 'Partille', active: true },
  { name: 'Effet AB', address: 'Box 50', city: 'Lindome', active: true },
  { name: 'Eklanda Screen', address: 'Fältspadsgatan 1', city: 'Västra Frölunda', active: true },
  { name: 'Electro Heat', address: 'Arendalsvarvet', city: 'Göteborg', active: true },
  { name: 'Electrotec Energy AB', address: 'Rannevägen 7', city: 'Varberg', active: true },
  { name: 'Engineering Force Sweden AB', address: 'Skårbyvägen 39', city: 'Kungsbacka', active: true },
  { name: 'Entrematic Group AB', address: 'Box 160', city: 'Torslanda', active: true },
  { name: 'Entrematic Sweden AB', address: 'Box 160', city: 'Torslanda', active: true },
  { name: 'ett2tre Höör', address: 'Box 34', city: 'Höör', active: true },
  { name: 'Express Delivery Sweden AB', address: 'Fack 913,FE 833', city: 'Uppsala', active: true },
  { name: 'Fagerhults Garden', address: 'Snapphaneallén 12', city: 'Skånes Fagerhult', active: true },
  { name: 'FERBE Tools AB', address: 'Baldersvägen 25', city: 'Gislaved', active: true },
  { name: 'Finn Sörensen Åkeri AB', address: 'Badviksvägen 62 b', city: 'Gunnilse', active: true },
  { name: 'First Cargo Sweden AB', address: 'Box 13121', city: 'Göteborg', active: true },
  { name: 'Fotö Hamnförening', address: 'Vändstigen 7', city: 'Fotö', active: true },
  { name: 'Fraktkedjan Väst Anläggning AB', address: 'Fraktvägen 2', city: 'Mölnlycke', active: true },
  { name: 'Fraktkedjan Väst Distribution AB', address: 'Exportgatan 15', city: 'Göteborg', active: true },
  { name: 'Frykens Trävaru AB', address: 'Box 2117', city: 'Karlstad', active: true },
  { name: 'Frölunda Transport', address: 'Fiskebäckshamn 20', city: 'Västra Frölunda', active: true },
  { name: 'Fulltlass Sweden AB', address: 'Söromberget 6', city: 'Ljusdal', active: true },
  { name: 'G Karlsson Spedition AB', address: 'Ljungadalsgatan 21', city: 'Växjö', active: true },
  { name: 'Galliker Transport&Logistik AB', address: 'Arendals alle 5', city: 'Göteborg', active: true },
  { name: 'Gasmontage AB', address: 'Arendalsvägen 27', city: 'Kungsbacka', active: true },
  { name: 'GB Framåt', address: 'Gullbergsvass Hus S', city: 'Göteborg', active: true },
  { name: 'GDL AB', address: 'Box 22301', city: 'Helsingborg', active: true },
  { name: 'Gerkes Byggmontage', address: 'Sjömärkesvägen 24', city: 'Torslanda', active: true },
  { name: 'Gisslen Trafik & Logistik AB', address: 'Gunnavägen PL3579', city: 'Lindome', active: true },
  { name: 'Gothia Automation', address: 'Fiskhamnsgatan 10', city: 'Göteborg', active: true },
  { name: 'Gothia Offset AB', address: 'Kärrlyckegatan 25', city: 'Göteborg', active: true },
  { name: 'GPP Perimeter Protection AB', address: 'Hägernäsvägen 25', city: 'Täby', active: true },
  { name: 'Gundals Åkeri AB', address: 'Heljesvägen 6', city: 'Lindome', active: true },
  { name: 'Gällö Såg AB', address: 'Box 303', city: 'Gällö', active: true },
  { name: 'Göteborgs lastbils komplettering', address: 'Östergärde ind omr', city: 'Göteborg', active: true },
  { name: 'Göteborgs Marin och kapellteknik', address: 'Redegatan 9', city: 'Västra Frölunda', active: true },
  { name: 'Hagagaraget AB', address: 'Surbrunnsgatan 49', city: 'Stockholm', active: true },
  { name: 'Hallands garageportar AB', address: '', city: '', active: true },
  { name: 'Hallens Transport AB', address: 'Hildedalsgatan 6', city: 'Göteborg', active: true },
  { name: 'HB Allt i Pool Väst', address: 'Stillestorpsvägen 5', city: 'Stenkullen', active: true },
  { name: 'Hedenskogs Åkeri AB', address: 'Holmvägen 75', city: 'Göteborg', active: true },
  { name: 'Hefa AB', address: 'Orrekulla industrigata 61', city: 'Hisings Kärra', active: true },
  { name: 'Henkel Norden AB', address: 'Aröds Industriväg 25-29', city: 'Hisings Backa', active: true },
  { name: 'Heri Kiruna AB', address: 'Maskinvägen 16', city: 'Kiruna', active: true },
  { name: 'HESA', address: '', city: '', active: true },
  { name: 'HLL Hyreslandslaget Mitt AB', address: '', city: '', active: true },
  { name: 'Holmgrens Väst AB', address: 'Gamla Kronvägen 14', city: 'Partille', active: true },
  { name: 'Huges Marina', address: 'Arnegårdsgatan 11', city: 'Mölndal', active: true },
  { name: 'Härjeåns Energi AB', address: 'Box 129', city: 'Sveg', active: true },
  { name: 'Högsbo Transport', address: 'Kryptongatan 14', city: 'Mölndal', active: true },
  { name: 'Hörmann Svenska AB', address: 'Skjutbanevägen 10', city: 'Örebro', active: true },
  { name: 'Ideåtgärd AB', address: 'Mätslingan 20', city: 'Täby', active: true },
  { name: 'Innerstadens Plåttjänst AB', address: 'Importgatan 14B', city: 'Göteborg', active: true },
  { name: 'Intergate AB', address: 'Hantverksgatan 14', city: 'Stenungsund', active: true },
  { name: 'Internationella Cityordonnansen AB', address: 'Arendalsvägen 21', city: 'Göteborg', active: true },
  { name: 'Isakssons Åkeri i Piteå AB', address: 'Norrfjärden', city: '', active: true },
  { name: 'Jari Safe AB', address: 'Rydsgatan 2', city: 'Tibro', active: true },
  { name: 'John Olsson i Skövde AB', address: 'Gruvgatan 4B', city: 'Skövde', active: true },
  { name: 'Jörgen Elv', address: '', city: '', active: true },
  { name: 'Jörgen Hansson', address: 'Torshällsvägen 14', city: 'Torslanda', active: true },
  { name: 'Kanndalen AB', address: 'Stranden 10', city: 'Öckerö', active: true },
  { name: 'KDB Sverige AB', address: 'Florettgatan 17', city: 'Helsingborg', active: true },
  { name: 'Kebelco AB', address: '', city: '', active: true },
  { name: 'Knarrholmen Drift AB', address: 'Bifrostgatan 42', city: 'Mölndal', active: true },
  { name: 'Knarrholmen Drift AB', address: '', city: '', active: true },
  { name: 'Kode Marin & Maskin', address: 'Hegil 130', city: 'Kode', active: true },
  { name: 'Kollibee AB', address: 'Box 14001', city: 'Göteborg', active: true },
  { name: 'Kuehne & Nagel', address: '', city: '', active: true },
  { name: 'Kungälvs Industri Rör', address: 'Skäggstorp 115', city: 'Kode', active: true },
  { name: 'KVD Kvarndammen AB', address: 'Ellesbovägen 150', city: 'Kungälv', active: true },
  { name: 'Kålltorps Handelsträdgård', address: 'Kyrkåsplatsen', city: 'Göteborg', active: true },
  { name: 'Källfelt Byggnads AB', address: 'Sven Källfelts gata 21', city: 'Västra Frölunda', active: true },
  { name: 'Kärr Lyse AB', address: 'Inlandsgatan 16-20', city: 'Göteborg', active: true },
  { name: 'Lager', address: '', city: '', active: true },
  { name: 'Lars Erik Jansson', address: 'Tegneby 120', city: 'Kode', active: true },
  { name: 'Lars Jonsson Entr AB', address: 'Hörnäsvägen 5', city: 'Själevad', active: true },
  { name: 'Laxå pellets AB', address: 'Logistikvägen', city: 'Röfors', active: true },
  { name: 'LBC Borås AB', address: 'Getängsvägen 18', city: 'Borås', active: true },
  { name: 'LBC Frakt i Värmland AB', address: 'Lovartsgatan 3', city: 'Karlstad', active: true },
  { name: 'LBC Logistik AB', address: 'Bojortsgatan 9', city: 'Kristinehamn', active: true },
  { name: 'Leksands Dörren AB', address: 'Siljansnäsvägen 12', city: 'Leksand', active: true },
  { name: 'Leman International Systemtransport.as', address: 'Vardevej 1', city: 'Aalborg', active: true },
  { name: 'Lennart Helmersson Åkeri', address: 'Mörkhedsvägen 32', city: 'Råneå', active: true },
  { name: 'Lima Bilfrakt AB', address: 'Bu 205', city: 'Lima', active: true },
  { name: 'Liveside Event AB', address: 'Mötterudsvägen 1', city: 'Arvika', active: true },
  { name: 'LogistikMäklaren i Kumla AB', address: 'Östra Gatan 57', city: 'Kumla', active: true },
  { name: 'LR Tryck i Sunne AB', address: 'Svetsarevägen 6', city: 'Sunne', active: true },
  { name: 'Lucie Transport AB', address: 'Gamla Kungsvägen 42', city: 'Alingsås', active: true },
  { name: 'Lundqvist Trävaru AB', address: 'Mejselvägen 28', city: 'Öjebyn', active: true },
  { name: 'Låsfixarn i Kiruna AB', address: 'Biblioteksgatan 7', city: 'Kiruna', active: true },
  { name: 'Lööve Nordic AB', address: 'Industrivägen 12', city: 'Boden', active: true },
  { name: 'M Åström Bastuprodukter', address: 'Robertsforsvägen 30', city: 'Bygdsiljum', active: true },
  { name: 'Magnus Kellerman', address: 'Kastellgatan 4', city: 'Göteborg', active: true },
  { name: 'Magnus&Roberts Transport AB', address: 'Älvvägen 5', city: 'Övertorneå', active: true },
  { name: 'MainGate Industridörrar AB', address: 'Box 1066', city: 'Vallentuna', active: true },
  { name: 'Majornas Lastbilar AB', address: 'Åskvädersgatan 7', city: 'Göteborg', active: true },
  { name: 'Marinteknik Torslanda AB', address: 'Björlanda Kile Småbåtshamn', city: 'Torslanda', active: true },
  { name: 'Mark & VA', address: 'Mellbyvägen 19', city: 'Partille', active: true },
  { name: 'Martin Sjöberg', address: 'Sjömarksvägen 20', city: 'Torslanda', active: true },
  { name: 'Mattssons Åkeri AB', address: 'Kärrlyckegatan 21', city: 'Göteborg', active: true },
  { name: 'Mectec i Boden AB', address: 'Industrivägen 12', city: 'Boden', active: true },
  { name: 'Metall Design Göteborg AB', address: 'Inlandsgatan 16', city: 'Göteborg', active: true },
  { name: 'Milos Rodic', address: '', city: '', active: true },
  { name: 'MIMAB', address: 'Indiska Oceanen 4', city: 'Göteborg', active: true },
  { name: 'Mittport AB-Garageportexperten', address: 'Trafikgatan 11', city: 'Sundsvall', active: true },
  { name: 'MM Nora', address: 'Råbyvägen 97', city: 'Uppsala', active: true },
  { name: 'Molenco AB', address: 'Mejselvägen 16', city: 'Skövde', active: true },
  { name: 'Molnsättra Gård AB', address: 'Molnsättra', city: 'Järfälla', active: true },
  { name: 'Montar Portar AB', address: 'Bondegatan 16B', city: 'Falkenberg', active: true },
  { name: 'Morgondagens Bryggeri', address: 'Turbingatan 10', city: 'Göteborg', active: true },
  { name: 'Måab bil & Maskin AB', address: 'Landhöjningsvägen 33', city: 'Hovås', active: true },
  { name: 'Mölndals Snickarn', address: 'Biskopbogatan 53', city: 'Mölndal', active: true },
  { name: 'N133 Örgryte-Härlanda', address: 'G40 Itraservice', city: 'Göteborg', active: true },
  { name: 'Nexans Norway AS', address: 'Postboks 166 Ökern', city: 'Oslo', active: true },
  { name: 'Nilfisk Advance AB', address: 'Box 4029', city: 'Mölndal', active: true },
  { name: 'Ninab Specialtransporter AB', address: 'Fjärhult 475', city: 'Nol', active: true },
  { name: 'Nippon Gases Sverige AB', address: 'Aröds Industriväg 2B', city: 'Hisings Backa', active: true },
  { name: 'NOKAB', address: 'Kågenäsvägen 10', city: 'Öckerö', active: true },
  { name: 'Nord Svenska Port', address: 'Handelsvägen 15 A', city: 'Luleå', active: true },
  { name: 'Nordcalott Trading AB', address: 'Vuonovägen 10', city: 'Haparanda', active: true },
  { name: 'Norden Tyres Group', address: 'Trädgårdsvägen 3-7', city: 'Tobo', active: true },
  { name: 'Nordic Crane AB', address: 'Box 816', city: 'Strömsund', active: true },
  { name: 'Nordicon Trucking AB', address: 'Box 7233', city: 'Göteborg', active: true },
  { name: 'Nordport AB', address: 'Skjutbanevägen 11 H', city: 'Örebro', active: true },
  { name: 'Nordvära Alltjänst AB', address: 'Nordvära 15', city: 'Väröbacka', active: true },
  { name: 'Norfolkline AB', address: 'Box 48083', city: 'Göteborg', active: true },
  { name: 'Norrskog Wood Products AB', address: 'Box 232', city: 'Kramfors', active: true },
  { name: 'NSC Sweden AB', address: 'Box 2138', city: 'Göteborg', active: true },
  { name: 'NTEX AB', address: 'Box 8702', city: 'Göteborg', active: true },
  { name: 'N-Tex Inrikes', address: 'FE553 PLU5001', city: 'Stockholm', active: true },
  { name: 'NWP Norrskog', address: 'nwp-faktura@norrskog.se', city: '', active: true },
  { name: 'Närkefrakts Huvudkontor', address: 'Transportgatan 4', city: 'Örebro', active: true },
  { name: 'Nöjesbyrån i Karlskoga AB', address: 'Labinhöjdsvägen 6', city: 'Karlskoga', active: true },
  { name: 'O.M.C. Ekspedeerimice to', address: '', city: '', active: true },
  { name: 'Olof Leander Måleri', address: 'August Barksgata 30A', city: 'Västra Frölunda', active: true },
  { name: 'Optimera Svenska AB/Göteborg', address: 'Box 11076', city: 'Bromma', active: true },
  { name: 'Orren Entreprenad AB', address: 'Box 1027', city: 'Kumla', active: true },
  { name: 'Pernilla Helsingius', address: 'Ruskpricksvägen 13', city: 'Torslanda', active: true },
  { name: 'Peter Andersson-Piltz', address: 'Risåsgatan 10B', city: 'Göteborg', active: true },
  { name: 'Peter Erlandssson', address: 'Morkullesträcket', city: 'Partille', active: true },
  { name: 'Petersson Transport AB Morgan', address: 'Östadsvägen 52', city: 'Gråbo', active: true },
  { name: 'Pia Karlsson Trp', address: 'Kallhedsstigen 7', city: 'Torslanda', active: true },
  { name: 'Polymerhuset AB', address: 'Klämman 39', city: 'Torslanda', active: true },
  { name: 'Port & Dörrteknik i Västerås AB', address: 'Fältmätargatan 7', city: 'Västerås', active: true },
  { name: 'Port&Snickericenter AB', address: 'Flöjebergsgatan 20c', city: 'Mölndal', active: true },
  { name: 'Portbolaget i Norden AB', address: 'Brikettgatan 2', city: 'Karlstad', active: true },
  { name: 'Portbolaget i Umeå AB', address: 'Kassjö 480', city: 'Umeå', active: true },
  { name: 'Portexperten i Kiruna AB', address: 'Biblioteksgatan 7', city: 'Kiruna', active: true },
  { name: 'Portexpo i Östersund AB', address: 'Odenskogsvägen 30', city: 'Östersund', active: true },
  { name: 'Portgiganten', address: 'Rimmaregatan 2', city: '', active: true },
  { name: 'Portlifv AB', address: 'Norra Gatan 3', city: 'Gävle', active: true },
  { name: 'Portmontören i Värmland AB', address: 'Fiskevik Höglunda', city: 'Arvika', active: true },
  { name: 'Portspecialisten Göteborg AB', address: 'Gröenvägen 9c', city: 'Landvetter', active: true },
  { name: 'Portspecialisten Örebro AB', address: 'Radiatorvägen 15', city: 'Örebro', active: true },
  { name: 'Porttjänst i Alingsås', address: 'Tomasgårdsvägen 17', city: 'Alingsås', active: true },
  { name: 'PostNord Logistics AB', address: 'Fack 610329 RO16', city: 'Stockholm', active: true },
  { name: 'Presto Brandsäkerhet AB', address: 'Box 315', city: 'Katrineholm', active: true },
  { name: 'Prido AB', address: 'Industrigatan 3', city: 'Tråvad', active: true },
  { name: 'Procedursvets Göteborg AB', address: 'Rönnvägen 20', city: 'Nygård', active: true },
  { name: 'R A Maskinservice', address: 'Box 652', city: 'Kungälv', active: true },
  { name: 'R.Olssons Åkeri AB', address: 'Smidesvägen 3', city: 'Sunne', active: true },
  { name: 'Ravesta Portservice AB', address: 'Ravesta 135', city: 'Arnäsvall', active: true },
  { name: 'Reco Port AB', address: 'Sockerbruksgatan 9', city: 'Lidköping', active: true },
  { name: 'Rejnäs villan Solma AB', address: 'Företagsvägen 2', city: 'Mölnlycke', active: true },
  { name: 'RHENUS LOGISTICS', address: '', city: '', active: true },
  { name: 'Robust Rullprofil AB', address: 'Södra vägen 6', city: 'Örebro', active: true },
  { name: 'Ronald Seger Transport AB', address: 'Fiskhamnsgatan 10', city: 'Göteborg', active: true },
  { name: 'Rupert Marine Production', address: 'Igeldammsgatan 34', city: 'Stockholm', active: true },
  { name: 'Ryds Båtar AB', address: 'Strandvägen 4', city: 'Ryd', active: true },
  { name: 'Räk & Laxgrossisten', address: 'Inlandsagatan', city: 'Göteborg', active: true },
  { name: 'Saile Stål AB', address: 'Ekenleden 11a', city: 'Kållered', active: true },
  { name: 'Sand Maritim AB', address: 'Klämman 39', city: 'Torslanda', active: true },
  { name: 'SBS Radio AB', address: 'Box 34108', city: 'Stockholm', active: true },
  { name: 'Scan Unit AB', address: 'V. Tallgatan 32', city: 'Helsingborg', active: true },
  { name: 'Scandterm', address: 'Kårebogatan 10', city: 'Göteborg', active: true },
  { name: 'Scanfor', address: '', city: 'Mölnlycke', active: true },
  { name: 'Schenker AB (Malmö)', address: 'Leverantsfakturor BOX 50434', city: 'Malmö', active: true },
  { name: 'S-E Westerlunds Åkeri AB', address: 'Hamngatan 3', city: 'Enköping', active: true },
  { name: 'Seacastle Göteborg', address: 'Grangatan 20', city: 'Mölndal', active: true },
  { name: 'Securegates Sweden AB', address: 'Teknikergatan 7', city: 'Kungälv', active: true },
  { name: 'SGF Garageportexperten Sverige AB', address: 'Gottorpsgatan 15', city: 'Linköping', active: true },
  { name: 'Sjöstadensvarv AB', address: 'Norra vägen 11', city: 'Mariestad', active: true },
  { name: 'Skanska Industrial Solutions AB', address: 'C8193', city: 'Rosersberg', active: true },
  { name: 'Skara Logistik AB', address: 'Saleby Dalen Jung 1', city: 'Kvänum', active: true },
  { name: 'SLT (Crawford Produktion AB)', address: 'Box 246 Hangarvägen 5', city: 'Torslanda', active: true },
  { name: 'Släpis AB', address: 'Exportgatan 24 B', city: 'Hisings Backa', active: true },
  { name: 'Släpvagnsgården', address: 'Lagmansholm Herrgård', city: 'Vårgårda', active: true },
  { name: 'Snabb Grus Sverige AB', address: 'Info@snabbgrus.se', city: '', active: true },
  { name: 'Sommer Aperto Scandinavia AB', address: 'Hantverksgatan 5D', city: 'Kungsbacka', active: true },
  { name: 'Sotefjordens Marina AB', address: 'Lökholmen', city: 'Hunnebostrand', active: true },
  { name: 'Spaldings i Göteborg AB', address: 'Synnerödsvägen 3', city: 'Göteborg', active: true },
  { name: 'Spedition Karl-Heinz Knauer e.K.', address: 'Ravensberg 10-12', city: 'Gettorf', active: true },
  { name: 'Spike Brewery', address: 'Slakthusområdet hus C', city: 'Göteborg', active: true },
  { name: 'STEA Sverige AB', address: 'Styckegodsgatan 7', city: 'Göteborg', active: true },
  { name: 'Stefan Nyträsk Allservice&transport AB', address: 'Lassvägen30', city: 'Luleå', active: true },
  { name: 'Stegcentralen i Årjäng AB', address: 'Box 30', city: 'Årjäng', active: true },
  { name: 'Stena Line Onboard Services AB', address: 'Account Payable', city: 'Göteborg', active: true },
  { name: 'Stena line Scandinavia AB', address: 'Utbetalningen', city: 'Göteborg', active: true },
  { name: 'Stenvalls Trä AB', address: 'Norrsågsvägen 39', city: 'Luleå', active: true },
  { name: 'Store Udds Samfällighetsförening', address: '', city: '', active: true },
  { name: 'Sundsfrakt AB', address: 'Box 750', city: 'Sunds vall', active: true },
  { name: 'Surte Åkeri AB', address: 'Kvarnvägen 3', city: 'Surte', active: true },
  { name: 'Svanströms Bygg & Trävaror', address: 'Skålviken 106', city: 'Hagfors', active: true },
  { name: 'Swedebridge AB', address: 'Blidögatan 25', city: 'Malmö', active: true },
  { name: 'Svensk Logistik Partner', address: 'Synnerödsvägen 10', city: 'Göteborg', active: true },
  { name: 'Svenska Poolfabriken AB', address: 'ålgatan 9', city: 'Luleå', active: true },
  { name: 'Säve Hyrmaskiner Sverige AB', address: '', city: '', active: true },
  { name: 'Talent plastics Göteborg AB', address: 'Bangårdsvägen 45', city: 'Kållered', active: true },
  { name: 'Teckentrup Scandinavia AB', address: 'Täljstensvägen 2', city: 'Stenkullen', active: true },
  { name: 'Terminal Skaraborg', address: 'Österängsg 4', city: 'Falköping', active: true },
  { name: 'T-H Pettersson AB', address: 'Box 14052', city: 'Göteborg', active: true },
  { name: 'TIMA Logistik AB', address: 'Hissgatan 2', city: 'Lidköping', active: true },
  { name: 'Timber Trading', address: '', city: '', active: true },
  { name: 'Tommy Nordbergh Åkeri AB', address: 'Brovägen 6', city: 'Hjärnarp', active: true },
  { name: 'Torslanda Träemballage AB', address: 'Flygfältsgatan 38', city: 'Torslanda', active: true },
  { name: 'Torverk Industrial Doors', address: 'Alstigen 2', city: 'Torsby', active: true },
  { name: 'Trancel Systems AB', address: 'Redegatan 7', city: 'Västra Frölunda', active: true },
  { name: 'Transportproduktion i Västerås AB', address: 'Box 20017', city: 'Västerås', active: true },
  { name: 'Transportservice Logistics AB', address: '', city: 'Örebro', active: true },
  { name: 'Transportören i Göteborg AB', address: 'Knipplekullagatan 3', city: 'Göteborg', active: true },
  { name: 'Trelleborg Sealing Profiles Swe AB', address: 'Kävsjövägen 38', city: 'Värnamo', active: true },
  { name: 'Trollenäs Schakt AB', address: 'Trollenäs 110', city: 'Eslöv', active: true },
  { name: 'UK-Portservice AB', address: 'Vävlagaregatan 15D', city: 'Brämhult', active: true },
  { name: 'Ulrika Horn af Rantzien', address: '', city: '', active: true },
  { name: 'Umeå Schenker AB', address: 'Leverantörsfakturor Box 50434', city: 'Malmö', active: true },
  { name: 'Unisport', address: 'Axeltoftavägen 180', city: 'Landskrona', active: true },
  { name: 'UniTeam AB', address: 'Flygfältsgatan 7', city: 'Torslanda', active: true },
  { name: 'UniWay A/S', address: '', city: '', active: true },
  { name: 'UPPDRAGET I GBG AB', address: 'Slakthusgatan 11', city: 'Göteborg', active: true },
  { name: 'Uppsala Garageportar AB', address: 'Onslunda 35', city: 'Vattholma', active: true },
  { name: 'Wadman Transport', address: 'Östra Hamnen 20', city: 'Hönö', active: true },
  { name: 'Vanerline Transportförmedling AB', address: 'Industrigatan 17', city: 'Hova', active: true },
  { name: 'Vanstad Svets & Mek HB', address: 'Brovägen 6', city: 'Hjärnarp', active: true },
  { name: 'Varla Bleck&Plåt AB', address: 'Magasinsgatan 10', city: 'Kungsbacka', active: true },
  { name: 'Veolia Recycling Solutions Sweden', address: 'Kryptongatan 16', city: 'Mölndal', active: true },
  { name: 'Westevent AB', address: 'Bergsätersgatan 21', city: 'Västra Frölunda', active: true },
  { name: 'WH Byggservice AB', address: 'EA Rosengrens Gata 31', city: 'Västra Frölunda', active: true },
  { name: 'VIBE Lots & Terminal AB', address: 'Kårebogatan 10', city: 'Göteborg', active: true },
  { name: 'Viktor Almen Shipping AB', address: 'Stavgatan 8', city: 'Strömstad', active: true },
  { name: 'Win Tec Fönsterteknik AB', address: 'Redegatan 4', city: 'Västra Frölunda', active: true },
  { name: 'Witab AB', address: 'Skalkorgarna 15', city: 'Torslanda', active: true },
  { name: 'Värnamo Krosskonsult AB', address: 'Drömminge', city: 'Bor', active: true },
  { name: 'Wärtsilä Sweden AB C/O Wärtsilä Finland', address: 'Wärtsilä shared service center Po.Box 409', city: 'Finland', active: true },
  { name: 'Västsvenska mur&plattsättning AB', address: 'Nordtångsvägen 18', city: 'Torslanda', active: true },
  { name: 'Västsvenska Port&El AB', address: 'Orrekulla Industrigatan 23', city: 'Hisings Kärra', active: true },
  { name: 'Västvärmlands LBC AB', address: 'Box 300', city: 'Arvika', active: true },
  { name: 'Xpressfrakt AB', address: 'Kålelundsvägen 21', city: 'Åsa', active: true },
  { name: 'XR Logistik AB', address: 'Box 30', city: 'Skövde', active: true },
  { name: 'Yanmar Sverige', address: '', city: '', active: true },
  { name: 'Åshammars Hyvleri & Trävaru AB', address: 'Bakfallsvägen 5', city: 'Åshammar', active: true },
  { name: 'Örneborgs Delikatesser AB', address: 'Södra Långbergsgatan 12', city: 'Västra Frölunda', active: true },
];

module.exports = {
  customers,
  vehicles,
  drivers,
};
